
//MIT License
//
//Copyright (c) 2022 bluetailtech
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.

package btt_bcalls;

import java.net.*;
import java.net.URLConnection.*;
import java.io.*;
import java.nio.*;
import java.util.*;

import java.io.File;
import java.io.IOException;

import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.*;
import javax.swing.*;

import javax.swing.filechooser.*;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.Files;
import java.io.*;
import java.awt.*;
import java.awt.event.*;

import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.HashSet;
import java.io.IOException;

public class btt_bcalls_frame extends javax.swing.JFrame
{
  Console console=null;
  uploader up=null;
  Config config=null;
  Thread up_thread=null;

  public btt_bcalls_frame()
  {
    initComponents();

    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/btt_bcalls/icon.png")).getImage()); // NOI18N

    console = new Console();
    jPanel4.add(console, java.awt.BorderLayout.CENTER);

    String version = "2022-07-01_1259";
    System.out.println("BTT BCalls Version "+version);
    jLabel1.setText("BTT BCalls Verson "+version);

    config = new Config();
    config.init();

    apikey_tf.setText(config.apikey);
    sid_tf.setText(config.node_id);
    p25_sys_id.setText(config.p25_sysid);
    base_path.setText(config.base_path);
    ffmpeg_path.setText(config.ffmpeg_bin);

    en_broadcastify_calls.setSelected( config.enabled );

    try {
      up = new uploader(config);
      up_thread = new Thread(up);
      if(config.enabled) up_thread.start();
    } catch(Exception e) {
    }

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        apikey_tf = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sid_tf = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        p25_sys_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        set_base_path = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        base_path = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        ffmpeg_set_path = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ffmpeg_path = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        test_ffmpeg = new javax.swing.JButton();
        test_result = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        update_configuration = new javax.swing.JButton();
        en_broadcastify_calls = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("BTT BCalls");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Assigned By Broadcastify Admin. Keep This Information Private!!"));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("API Key");
        jPanel6.add(jLabel2);

        apikey_tf.setColumns(64);
        jPanel6.add(apikey_tf);

        jPanel5.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Assigned By Broadcastify Admin"));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("SID (NODE-ID)");
        jPanel7.add(jLabel3);

        sid_tf.setColumns(10);
        jPanel7.add(sid_tf);

        jPanel5.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("The System ID Of The Monitored System Associated With The Assigned Key/SID Pair (decimal)"));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("SYSTEM_ID");
        jPanel8.add(jLabel4);

        p25_sys_id.setColumns(12);
        jPanel8.add(p25_sys_id);

        jLabel5.setText("(decimal) Note: This is the system id of the system you are monitoring");
        jPanel8.add(jLabel5);

        jPanel5.add(jPanel8);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Path To Wav File Dir"));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        set_base_path.setText("Set Path");
        set_base_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_base_pathActionPerformed(evt);
            }
        });
        jPanel13.add(set_base_path);

        jSeparator3.setMinimumSize(new java.awt.Dimension(50, 0));
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 0));
        jPanel13.add(jSeparator3);

        base_path.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        base_path.setText("/home/p25rx/broadcastify_calls");
        jPanel13.add(base_path);

        jSeparator4.setMinimumSize(new java.awt.Dimension(50, 0));
        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 0));
        jPanel13.add(jSeparator4);

        jPanel12.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel6.setText("      Filename Mask: TG_ID_TIMESECS_SYSID_RID_DURATION_.wav");
        jPanel14.add(jLabel6);

        jSeparator5.setPreferredSize(new java.awt.Dimension(50, 0));
        jPanel14.add(jSeparator5);

        jLabel7.setText("Example:TG_317_1656616227_842_857937500_742467_6.5_.wav ");
        jPanel14.add(jLabel7);

        jPanel12.add(jPanel14);

        jPanel5.add(jPanel12);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Path To FFMPEG Executable"));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        ffmpeg_set_path.setText("Set Path");
        ffmpeg_set_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffmpeg_set_pathActionPerformed(evt);
            }
        });
        jPanel9.add(ffmpeg_set_path);

        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 0));
        jPanel9.add(jSeparator1);

        ffmpeg_path.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ffmpeg_path.setText("/usr/bin/ffmpeg");
        jPanel9.add(ffmpeg_path);

        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 0));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 0));
        jPanel9.add(jSeparator2);

        jPanel5.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        test_ffmpeg.setText("Test FFMPEG");
        test_ffmpeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_ffmpegActionPerformed(evt);
            }
        });
        jPanel10.add(test_ffmpeg);

        test_result.setText("Result:");
        jPanel10.add(test_result);

        jPanel5.add(jPanel10);

        update_configuration.setText("Update Config");
        update_configuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_configurationActionPerformed(evt);
            }
        });
        jPanel11.add(update_configuration);

        en_broadcastify_calls.setText("Enable RR Broadcastify Calls Uploader");
        en_broadcastify_calls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                en_broadcastify_callsActionPerformed(evt);
            }
        });
        jPanel11.add(en_broadcastify_calls);

        jPanel5.add(jPanel11);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Configuration", jPanel2);

        jPanel4.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Log", jPanel4);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


  private void ffmpeg_set_pathActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ffmpeg_set_pathActionPerformed
  {
    try {
      JFileChooser chooser = new JFileChooser();

      int returnVal = chooser.showDialog(this, "Path To FFMPEG Executable");

      if(returnVal == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        config.ffmpeg_bin = file.getAbsolutePath();
        ffmpeg_path.setText( file.getAbsolutePath() );
        update_config();
      }

    } catch(Exception e) {
      e.printStackTrace();
    }
  }//GEN-LAST:event_ffmpeg_set_pathActionPerformed

  private void test_ffmpegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_test_ffmpegActionPerformed
  {
    try {
      if( up.is_m4a_supported() ) {
        test_result.setText("Result: M4A/AAC Audio is supported");
        return;
      } else if( up.is_mp3_supported() ) {
        test_result.setText("Result: MP3 Audio is supported");
        return;
      } else {
        test_result.setText("Result: Couldn't determine MP3 / M4A support. incorrect path to ffmpeg?");
      }
    } catch(Exception e) {
    }
  }//GEN-LAST:event_test_ffmpegActionPerformed

  private void en_broadcastify_callsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_en_broadcastify_callsActionPerformed
  {
    try {
      config.enabled = en_broadcastify_calls.isSelected();
      update_config();
      if(config.enabled && !up_thread.isAlive()) up_thread.start();
    } catch(Exception e) {
      e.printStackTrace();
    }
  }//GEN-LAST:event_en_broadcastify_callsActionPerformed

  private void set_base_pathActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_set_base_pathActionPerformed
  {
    try {
      JFileChooser chooser = new JFileChooser();
      chooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );

      int returnVal = chooser.showDialog(this, "Path To Broadcastify Calls .wav Dir");

      if(returnVal == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        config.base_path = file.getAbsolutePath();
        base_path.setText( file.getAbsolutePath() );
        update_config();
      }

    } catch(Exception e) {
      e.printStackTrace();
    }
  }//GEN-LAST:event_set_base_pathActionPerformed

  public void update_config()
  {
    try {
      //config.ffmpeg_bin = "";
      //config.base_path = "";
      config.apikey=apikey_tf.getText();
      config.node_id=sid_tf.getText();
      config.p25_sysid=p25_sys_id.getText();

      config.update();
    } catch(Exception e) {
      e.printStackTrace();
    }
  }
  private void update_configurationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_update_configurationActionPerformed
  {
    update_config();
  }//GEN-LAST:event_update_configurationActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(btt_bcalls_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(btt_bcalls_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(btt_bcalls_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(btt_bcalls_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new btt_bcalls_frame().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField apikey_tf;
    public javax.swing.JLabel base_path;
    public javax.swing.JCheckBox en_broadcastify_calls;
    public javax.swing.JLabel ffmpeg_path;
    private javax.swing.JButton ffmpeg_set_path;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField p25_sys_id;
    private javax.swing.JButton set_base_path;
    public javax.swing.JTextField sid_tf;
    private javax.swing.JButton test_ffmpeg;
    private javax.swing.JLabel test_result;
    private javax.swing.JButton update_configuration;
    // End of variables declaration//GEN-END:variables
}
